=== antoniocmizv/LMSGI/XML/Ejercicios/ejercicio2/ejemplo.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

	<xs:element name="biblioteca">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="libro" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="titulo" type="xs:string" />
							<xs:element name="autor" type="xs:string" />
							<xs:element name="editorial" type="Tipo_editorial" />
							<xs:element name="año" type="xs:string" />
							<xs:element name="precio" type="Tipo_precio" />
							<xs:element name="tapa" type="Tipo_tapa" />
						</xs:sequence>
						<xs:attribute name="isbn" type="Tipo_Isbn" />
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:simpleType name="Tipo_precio">
		<xs:restriction base="xs:decimal">
			<xs:minInclusive value="2" />
			<xs:maxInclusive value="100" />
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="Tipo_tapa">
		<xs:restriction base="xs:string">
			<xs:enumeration value="dura" />
			<xs:enumeration value="blanda" />
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="Tipo_editorial">
		<xs:restriction base="xs:string">
			<xs:minLength value="5" />
			<xs:maxLength value="100" />
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="Tipo_Isbn">
		<xs:restriction base="xs:string">
			<xs:pattern value="[0-9]{13}" />
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="Tipo_tapa2">
		<xs:restriction base="xs:string">
			<xs:pattern value="dura|blanda" />
		</xs:restriction>
	</xs:simpleType>
	<xs:complexType name="tipo_editorial2">
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute name="codigo" type="xs:positiveInteger" />
			</xs:extension>
		</xs:simpleContent>

	</xs:complexType>

</xs:schema>

=== antoniocmizv/LMSGI/XML/ejemplo.xml
<?xml version="1.0" encoding="utf-8"?>
<biblioteca xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:noNamespaceSchemaLocation="ejemplo.xsd">
    <libro isbn="1o">
        <titulo>El Quijote</titulo>
        <autor>Miguel de Cervantes</autor>
        <editorial>Castalia</editorial>
        <año>1605</año>
        <precio>25.00</precio>
        <tapa>blanda</tapa>
        
    </libro>
    <libro isbn="2o">
        <titulo>Otro libro</titulo>
        <autor>Nombre del autor</autor>
        <editorial>Nombre de la editorial</editorial>
        <año>Año de publicación</año>
        <precio>20.55</precio>
        <tapa>dura</tapa>
    </libro>
    

</biblioteca>
